modLoader = "javafml"
loaderVersion = "[37,)"
license = "MIT"

[[mods]]
modId = "krasyrum"
version = "0.0.1"
displayName = "The Krasyrum"
logoFile = "logo.png"
credits = ""
authors = "DargonBoi"
description = '''
Extra Materials For Minecraft.
'''